### ISSUE TITLE
ruby_block 'get log_forward resources' always notifies

### ISSUE THREAD

**Issue by wfindley** [parallels-cookbooks/cookbook-logstash-forwarder#1]
I'm not sure how much of its elegance would have to be sacrificed, but I think there needs to be an `only_if` statement in there somewhere.

https://docs.chef.io/resource_common.html#only-if-examples

**Comment by Kasen** [comment]
Hi, wfindley.

ruby_block always notifies because it always runs. And i think it should run on every chef run.
What kind of problem it causes you?

**Comment by wfindley** [comment]
There's no functional problem with the cookbook. My understanding is just that chef runs that don't do anything should notify 0 resources.

**Comment by Kasen** [comment]
Actually ruby_block always searches resources in the run_context, so it sends notifications.
