### ISSUE TITLE
General question ?

### ISSUE THREAD

**Issue by BarthV** [parallels-cookbooks/cookbook-logstash-forwarder#2]
You created and published on supermarket this cookbook 2 weeks ago.

But there is already a living logstash_forwarder cookbook for almost a year on Chef supermarket (ok the '_' in the name is not very good .. but that's not a problem) :
- https://github.com/zeroXten/logstash_forwarder
- https://supermarket.chef.io/cookbooks/logstash_forwarder

What are the goals and the differences with the existing one that leads you to write "yet-another-cookbook-for-**" ...
Maybe the first one was not good enough ? But why not trying to PR ?
Can you explain to the community your motivations ?

Thanks !  :smile:

**Comment by Kasen** [comment]
Thanks for feedback. ✨👍

Before I published this cookbook to the super market, I wrote the letter to @zeroXten and discussed with him the future of our cookbooks. We decided, what @zeroXten will make his cookbook deprecated and will publish link to my cookbook.

**Comment by BarthV** [comment]
Ok nice to hear the communication is still awesome in Chef community :)
