### ISSUE TITLE
Provider broken

### ISSUE THREAD

**Issue by bcwilsondotcom** [parallels-cookbooks/cookbook-logstash-forwarder#9]
When running chef with cookbook version 0.2.1, the chef run fails with the following error:
# 
# Recipe Compile Error in /var/cache/chef/cookbooks/logstash-forwarder/providers/default.rb
## NoMethodError

undefined method `provides' for #Class:0x000000045b6540
## Cookbook Trace:

  /var/cache/chef/cookbooks/logstash-forwarder/providers/default.rb:9:in `class_from_file'
## Relevant File Content:

/var/cache/chef/cookbooks/logstash-forwarder/providers/default.rb:

  2:  # Cookbook Name:: logstash-forwarder
  3:  # Provider:: log_forward
  4:  # Author:: Kirill Kouznetsov agon.smith@gmail.com
  5:  #
  6:  # Copyright (c) 2015, Parallels IP Holdings GmbH
  7:  #
  8:
  9>> provides :log_forward
 10:
 11:  use_inline_resources if defined?(use_inline_resources)
 12:
 13:  action :create do
 14:  end
 15:

**Comment by Kasen** [comment]
Method 'provides' appeared in the Chef 12.
You are trying to run this cookbook under chef 11?

**Comment by bcwilsondotcom** [comment]
Ah, I see. Yeah, I'm trying to run this under chef 11.
